
directives:
- add_directives:
    file: package://manipulation/two_bins.dmd.yaml

- add_frame:
    name: camera0_origin
    X_PF:
        base_frame: world
        rotation: !Rpy { deg: [-158.0, 0, 90.0]}
        translation: [.21, -.5, .4]

- add_model:
    name: camera0
    file: file:///workspaces/mit-6.4212-belief-space-rrt/config/camera_box_no_collision.sdf

- add_weld:
    parent: camera0_origin
    child: camera0::base

- add_frame:
    name: camera1_origin
    X_PF:
        base_frame: world
        rotation: !Rpy { deg: [-163., 0, 0.0]}
        translation: [-0.05, -.66, .5]

- add_model:
    name: camera1
    file: file:///workspaces/mit-6.4212-belief-space-rrt/config/camera_box_no_collision.sdf

- add_weld:
    parent: camera1_origin
    child: camera1::base

- add_frame:
    name: camera2_origin
    X_PF:
        base_frame: world
        rotation: !Rpy { deg: [-158., 0, -90.0]}
        translation: [-.31, -.5, .4]

- add_model:
    name: camera2
    file: file:///workspaces/mit-6.4212-belief-space-rrt/config/camera_box_no_collision.sdf

- add_weld:
    parent: camera2_origin
    child: camera2::base

- add_frame:
    name: camera3_origin
    X_PF:
        base_frame: world
        rotation: !Rpy { deg: [-158.0, 0, 180.0]}
        translation: [0.50, 0.31, 0.40]

- add_model:
    name: camera3
    file: file:///workspaces/mit-6.4212-belief-space-rrt/config/camera_box_no_collision.sdf

- add_weld:
    parent: camera3_origin
    child: camera3::base

- add_frame:
    name: camera4_origin
    X_PF:
        base_frame: world
        rotation: !Rpy { deg: [-163.0, 0, 90.0]}
        translation: [0.66, 0.05, 0.50]

- add_model:
    name: camera4
    file: file:///workspaces/mit-6.4212-belief-space-rrt/config/camera_box_no_collision.sdf

- add_weld:
    parent: camera4_origin
    child: camera4::base

- add_frame:
    name: camera5_origin
    X_PF:
        base_frame: world
        rotation: !Rpy { deg: [-158.0, 0, 0.0]}
        translation: [0.50, -0.21, 0.40]

- add_model:
    name: camera5
    file: file:///workspaces/mit-6.4212-belief-space-rrt/config/camera_box_no_collision.sdf

- add_weld:
    parent: camera5_origin
    child: camera5::base
